import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'background':                '#fdf9ef',
        'on-background':             '#1c1c16',
        'surface':                   '#fdf9ef',
        'surface-dim':               '#dddad0',
        'surface-bright':            '#fdf9ef',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f7f3e9',
        'surface-container':         '#f1eee4',
        'surface-container-high':    '#ece8de',
        'surface-container-highest': '#e6e2d8',
        'surface-variant':           '#e6e2d8',
        'on-surface':                '#1c1c16',
        'on-surface-variant':        '#444748',
        'primary':                   '#390002',
        'primary-container':         '#600007',
        'on-primary':                '#ffffff',
        'on-primary-container':      '#ff5b53',
        'secondary':                 '#005faf',
        'secondary-container':       '#54a0fe',
        'on-secondary':              '#ffffff',
        'on-secondary-container':    '#003567',
        'tertiary':                  '#181816',
        'tertiary-container':        '#2d2c2a',
        'on-tertiary':               '#ffffff',
        'error':                     '#ba1a1a',
        'error-container':           '#ffdad6',
        'on-error':                  '#ffffff',
        'on-error-container':        '#93000a',
        'outline':                   '#747878',
        'outline-variant':           '#c4c7c7',
        'inverse-surface':           '#31312a',
        'inverse-on-surface':        '#f4f0e6',
        'inverse-primary':           '#ffb3ac',
      },
      fontFamily: {
        headline: ['Special Elite', 'Courier Prime', 'Courier New', 'serif'],
        body:     ['Special Elite', 'Courier Prime', 'Courier New', 'serif'],
        label:    ['Special Elite', 'Courier Prime', 'Courier New', 'monospace'],
        mono:     ['Courier Prime', 'Courier New', 'Special Elite', 'monospace'],
        marker:   ['Permanent Marker', 'Special Elite', 'Courier New', 'cursive'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
} satisfies Config
